### ISSUE TITLE
Edit Fish - negative channel and activation time values

### ISSUE THREAD

**Issue by dniklaus** [ERNICommunity/iof-admin#2]
The Channel range shall be 1..n.
The Activation Time shall be 0..m

![iof-admin-bug1_negative_channel](https://cloud.githubusercontent.com/assets/6551647/14456197/f77b69ba-00a3-11e6-89b3-ac3c36d49925.png)

**Comment by chriszuercher** [comment]
Will do it later

**Comment by chriszuercher** [comment]
channel: 1 ... n = 1 ... 1000
time: 0 ... m = 1 .... 10 (not implemented yet in Swagger API)
